ZcashFoundation/frost

frost-ristretto255/src/frost.rs
frost-ristretto255/src/frost/keys.rs
frost-ristretto255/src/frost/round1.rs
frost-ristretto255/src/frost/round2.rs
frost-ristretto255/src/frost/tests.rs
frost-ristretto255/src/frost/tests/vectors.json
frost-ristretto255/src/frost/tests/vectors.rs
frost-ristretto255/src/lib.rs
frost-ristretto255/tests/frost.rs

Including some docs and updated test vectors.
Resolves #32

Draft spec version 03 update

---

README.md
frost-core/src/frost/round1.rs
frost-core/tests/frost.rs
frost-p256/src/lib.rs
frost-p256/tests/frost.rs
frost-ristretto255/src/lib.rs
frost-ristretto255/tests/frost.rs

Closes https://github.com/ZcashFoundation/frost/issues/78

add commit(), use it instead of preprocess()

---

frost-core/src/frost.rs
frost-core/src/frost/round2.rs
frost-core/src/tests/vectors.rs
frost-core/tests/common/vectors.json
frost-p256/src/tests/vectors.json
frost-ristretto255/src/tests/vectors.json

use per-signer Rho per V7 spec

---

frost-core/src/frost/round1.rs
frost-core/src/tests/vectors.rs

Closes #133 
I also did a small refactoring so that test vectors are represented as a struct instead of a tuple.

Add nonce_generate test with test vectors

---

frost-core/src/frost.rs

Depends on #114 
Just a small optimization which was a TODO in the code, no issue for it

use BTreeMap for BindingFactorList

---

frost-core/src/lib.rs
frost-core/src/tests.rs

The changes in this PR were originally review suggestions for #159, but I didn't manage to submit them before #159 got merged.

Remove unnecessary casts to `Ciphersuite`

---

frost-core/src/frost/keys/dkg.rs
frost-core/src/tests.rs
frost-ed25519/dkg.md
frost-ed25519/src/lib.rs
frost-p256/dkg.md
frost-p256/src/lib.rs
frost-ristretto255/dkg.md
frost-ristretto255/src/lib.rs
gendoc/src/main.rs

Improve DKG API; add DKG example

---

.github/workflows/main.yml
frost-ed25519/dkg.md
frost-p256/dkg.md
frost-secp256k1/dkg.md
frost-secp256k1/src/lib.rs
gendoc/src/main.rs

Closes #174 
This also fixes gendoc to work with secp256k1 (another reason why we need this PR :laughing: )
This is failing on purpose to show it works. After it's reviewed I'll commit the updated files

add gendoc --check, use in CI

---

frost-core/Cargo.toml
frost-ed25519/Cargo.toml
frost-ed448/Cargo.toml
frost-p256/Cargo.toml
frost-ristretto255/Cargo.toml
frost-secp256k1/Cargo.toml

@conradoplg added you as an author on `frost-core`

release: prepping Cargo.toml's for crates.io release

---

frost-core/src/frost.rs
frost-secp256k1/Cargo.toml

Implements https://github.com/cfrg/draft-irtf-cfrg-frost/pull/360

improve aggregate performance by verifying the aggregate signature first

---

gendoc/src/main.rs

I used `gendoc` to auto generate some boilerplate benchmark code for https://github.com/ZcashFoundation/frost/pull/205 but ended up not actually adding that to `gendoc` because the generated code would need to be `rustfmt`-ed and it doesn't seem to be worth the effort to change it to do that.
But while doing that I also simplified gendoc a bit, it now uses a single list of string replacements instead of one for each usage (which is not an issue since they don't interfere with each other). It looks better so I created this PR with that change.

simplify gendoc

---

README.md
frost-core/src/benches.rs
frost-core/src/frost.rs
frost-core/src/frost/round2.rs
frost-rerandomized/src/lib.rs
gendoc/src/main.rs

Closes #202 
Co-authored-by: conrado <conrado@zfnd.org>

Rename derive_lagrange_coefficient to derive_interpolating_value

---

frost-rerandomized/src/lib.rs

This is basically the same as #207 but for `frost-rerandomized`.

frost-rerandomized: add aggregate optimization

---

.github/workflows/coverage.yaml
README.md

Improve accuracy of coverage reports 231

---

book/src/dev/frost-dependencies-for-audit.md

Add more some details about the FROST dependencies that are out of scope of the audit

Update FROST scope dependencies

---

.github/workflows/coverage.yaml
.github/workflows/main.yml
Cargo.toml
README.md
gencode/Cargo.toml
gencode/src/main.rs

renamed gendoc to gencode; make it unpublishable

---

frost-core/Cargo.toml
frost-ed25519/Cargo.toml
frost-ed25519/src/lib.rs
frost-ristretto255/Cargo.toml
frost-ristretto255/src/lib.rs

Update curve25519-dalek to 4.0.0-rc.1

---

frost-p256/Cargo.toml
frost-p256/src/lib.rs

Also fix the clippy warning (rule was renamed)

update p256 to 0.13.0

---

.gitignore
frost-core/src/benches.rs
frost-core/src/frost/keys.rs
frost-core/src/tests.rs
frost-ed25519/README.md
frost-ed25519/src/lib.rs
frost-ed448/README.md
frost-ed448/src/lib.rs
frost-p256/README.md
frost-p256/src/lib.rs
frost-rerandomized/src/tests.rs
frost-ristretto255/README.md
frost-ristretto255/src/lib.rs
frost-secp256k1/README.md
frost-secp256k1/src/lib.rs

Update keygen_with_dealer to return a hashmap

---

frost-ed25519/src/lib.rs
frost-ed448/src/lib.rs
frost-p256/src/lib.rs
frost-ristretto255/src/lib.rs
frost-secp256k1/src/lib.rs
gencode/src/main.rs

move comments before attributes; make gencode handle them

---

frost-core/CHANGELOG.md
frost-core/Cargo.toml
frost-ed25519/Cargo.toml
frost-ed448/Cargo.toml
frost-p256/Cargo.toml
frost-rerandomized/Cargo.toml
frost-ristretto255/Cargo.toml
frost-secp256k1/Cargo.toml

There's a breaking change so we actually need to bump to 0.2.0

bump version to 0.2.0, update changelog

---

.github/workflows/docs.yml

I've created the `frost-book` Firebase project but couldn't create the service account key for it as the key gen  permissions seem to be locked down.: https://github.com/w9jds/firebase-action

create docs.yml workflow

---

book/src/dev/frost-dependencies-for-audit.md

https://frost-book--pr313-dconnolly-patch-1-xap3unmf.web.app/dev/frost-dependencies-for-audit.html

Bumped our frost-* versions inline with our crate releases

---

frost-core/src/scalar_mul.rs

Ed448 looks to be working correctly so

Make multiscalar multiplication generic for any scalar field size

---

gencode/src/main.rs

This avoids CI failing if it wrongly detects unformatted code as a stale gencode-generated file

format Rust code generated by gencode

---

.mergify.yml

Update mergify yaml

---

frost-core/CHANGELOG.md
frost-ed25519/src/lib.rs
frost-ed448/src/lib.rs
frost-p256/src/lib.rs
frost-ristretto255/src/lib.rs
frost-secp256k1/src/lib.rs

Expose signing share in ciphersuite libraries

---

book/src/frost.md
book/src/tutorial/dkg.md
performance.md

I found some small typos and grammatical quirks here and there. Nothing of great importance 😅

ZF FROST Book text proof-read/review

---

frost-rerandomized/src/lib.rs
frost-rerandomized/src/tests.rs

Closes https://github.com/ZcashFoundation/frost/issues/359

add RandomizedParams::from_randomizer()

---

frost-core/src/frost/keys.rs

Fixes https://github.com/ZcashFoundation/frost/issues/463 and https://github.com/ZcashFoundation/frost/issues/464

fix some docs issues from audit

---

frost-core/src/frost.rs

Closes https://github.com/ZcashFoundation/frost/issues/447

update spec links

---

frost-core/src/frost.rs
frost-core/src/frost/round1.rs
frost-rerandomized/src/lib.rs

Closes https://github.com/ZcashFoundation/frost/issues/448
Also fixes two current doc warnings

fix misc docs issues

---

frost-core/src/tests/ciphersuite_generic.rs

Closes https://github.com/ZcashFoundation/frost/issues/504
Turns out I already had implemented the check :facepalm: but I did write a test for it in this PR

check if the part3() identifier consistency check works

---

frost-core/CHANGELOG.md
frost-core/src/frost/keys/dkg.rs

Closes https://github.com/ZcashFoundation/frost/issues/462

fix DKG challenge hashing order to match paper

---

book/src/tutorial/importing.md
frost-core/CHANGELOG.md
frost-core/Cargo.toml
frost-ed25519/Cargo.toml
frost-ed448/Cargo.toml
frost-p256/Cargo.toml
frost-rerandomized/Cargo.toml
frost-ristretto255/Cargo.toml
frost-secp256k1/Cargo.toml

bump versions and update changelog for 0.7.0 release

---

book/src/SUMMARY.md
book/src/dev/release-checklist.md

Part of https://github.com/ZcashFoundation/frost/issues/190
Copied from the google doc and reviewed.

book: add release checklist

---

README.md
book/src/SUMMARY.md
book/src/dev/developer-guide.md

update README, move dev info to book

---

book/book.toml
book/mdbook-admonish.css
book/src/dev/release-checklist.md
book/src/tutorial/importing.md
frost-core/CHANGELOG.md
frost-core/Cargo.toml
frost-ed25519/Cargo.toml
frost-ed448/Cargo.toml
frost-p256/Cargo.toml
frost-rerandomized/Cargo.toml
frost-ristretto255/Cargo.toml
frost-secp256k1/Cargo.toml

This updates the versions and changelog for release v1.0.0-rc.0 and closes #552

Release v1.0.0-rc.0

---

book/book.toml
book/mdbook-admonish.css
book/src/zcash/ywallet-demo.md

Update demo instructions in book

---

frost-core/CHANGELOG.md
frost-core/src/signing_key.rs

frost-core: expose SigningKey::to/from_scalar()

---

frost-core/CHANGELOG.md
frost-core/Cargo.toml
frost-core/src/keys.rs
frost-core/src/keys/dkg.rs
frost-core/src/lib.rs
frost-core/src/round1.rs
frost-core/src/round2.rs
frost-core/src/serialization.rs
frost-core/src/tests/ciphersuite_generic.rs
frost-ed25519/Cargo.toml
frost-ed448/Cargo.toml
frost-p256/Cargo.toml
frost-rerandomized/Cargo.toml
frost-ristretto255/Cargo.toml
frost-secp256k1/Cargo.toml

Closes #629 
I also backported some fixes from #535 that were not strictly related to no-std

Fix --no-default-features

---

.github/workflows/main.yml

ci: use cargo-all-features

---

frost-rerandomized/Cargo.toml
frost-rerandomized/src/lib.rs

randomized: add Debug to structs

---

frost-core/src/keys.rs
frost-core/src/lib.rs
frost-core/src/round1.rs
frost-core/src/round2.rs
frost-core/src/traits.rs
frost-ed25519/src/lib.rs
frost-ed448/src/lib.rs
frost-p256/src/lib.rs
frost-ristretto255/src/lib.rs
frost-secp256k1/src/lib.rs

Closes #225 :tada: 
I also went over each one and fixed broken links.

docs: update spec links to the final URL

---

frost-p256/src/lib.rs
frost-secp256k1/src/lib.rs

chore(frost-p256, frost-secp256k1): do not use allocator for domain separators

---

frost-core/src/keys.rs

Closes https://github.com/ZcashFoundation/frost/issues/825

frost-core: remove unneeded code

---

frost-core/src/round1.rs
frost-core/src/round2.rs
frost-core/src/signature.rs
frost-core/src/signing_key.rs
frost-core/src/tests/ciphersuite_generic.rs
frost-core/src/tests/refresh.rs

Some stuff is breaking in some combinations of features

all: fix issues related to features

---

book/src/frost.md

Update documentation to reflect the fact that Refreshing shares is now implemented for DKG

doc: Refreshing shares is now implemented for DKG

---

book/src/dev/release-checklist.md
frost-core/src/keys/dkg.rs

**wil - will**
**pubic - public**
fix typos , thanks

fix errors 

---

book/src/zcash/technical-details.md

As per the title - I was reading the book and saw this small typo, so here's a PR to fix it :)

Fixing a small typo

---

.github/workflows/coverage.yaml
.github/workflows/docs.yml
.github/workflows/main.yml
book/src/dev/developer-guide.md

chore(ci): update some github action dependencies

---

Cargo.toml
book/src/tutorial/importing.md
book/src/tutorial/signing.md
frost-core/CHANGELOG.md

Closes https://github.com/ZcashFoundation/frost/issues/913

bump to 2.2.0
