README.md, frost-core/README.md
Top level is ok (example will be updated when `frost-ristretto255` is updated to use `frost-core`), `frost-core` will get fleshed out more as the rest of the types are generic-ized over the `Ciphersuite`s
=> Add README.md for frost-core and update for root of repo

Cargo.toml, frost-p256/Cargo.toml, frost-p256/README.md, frost-p256/src/lib.rs, frost-p256/src/tests.rs, frost-p256/src/tests/vectors.json, frost-p256/src/tests/vectors.rs, frost-p256/tests/frost.rs, frost-p256/tests/proptests.rs
Adds P-256 support. Some notes:
- I didn't include a benchmark because they seem to be currently broken
- My first approach to represent the point encoding was `p256::Encoding`, which handles automatically the annoying identity encoding which takes a single byte. However that ends up causing other problems. I switched to a fixed array in 3c13b9cf. (I realized just after that V5 of the spec does specify that it should be a fixed-length array, so that's better anyway). The only uncertain thing is how the encode the identity, as we discussed in chat. For now I'm just padding it with zeroes.
- There's a lot of repetition in the tests, it's almost everything just a copy-and-paste of ristretto. I wonder if we should make them generic over the ciphersuite?
=> Add P-256 support

frost-core/src/frost.rs
Part of https://github.com/ZcashFoundation/frost/issues/60
=> use a single scalarmul in compute_group_commitment per v5 spec

frost-core/src/frost/keys.rs, frost-core/src/frost/round1.rs, frost-core/src/lib.rs, frost-core/tests/common/ciphersuite.rs, frost-core/tests/common/vectors.json, frost-core/tests/frost.rs, frost-p256/src/lib.rs, frost-p256/src/tests/vectors.json, frost-p256/tests/frost.rs, frost-ristretto255/src/lib.rs, frost-ristretto255/src/tests/vectors.json, frost-ristretto255/tests/frost.rs
Depends on #84 
Closes #75 (I would need to update the `order()` documentation so I went ahead and removed it)
Closes #60, #67, #80
- I'm not sure what to do with `cofactor()`. It's not used anymore in the spec, and it was removed from the verification procedure. But it seems we will need it back again for V7 so it seems we can just leave it. (Currently it's there, and it's still being used in verification)
- `SigningKey::sign` was not changed to use `nonce_generate`. I see these approaches:
1. Create a `nonce_generate` function, make `Nonce::new` and `SigningKey::sign` use it (currently the logic is in `Nonce::new`). In which module to put it, though?
1. Move `Nonce` out of `round1` and into the root module or `signing_key` module, change `Nonce::new` to receive a `Scalar` instead of …
=> Add nonce_generate function, update test vectors for V5

frost-core/src/frost/identifier.rs, frost-p256/src/lib.rs, frost-ristretto255/src/lib.rs
Depends on https://github.com/ZcashFoundation/frost/pull/87
Fix some clippy lints, but not all; there are a lot of them in `frost-redjujub` and I figured it wasn't worth fixing them since that code will be replaced in the future.
=> Fix clippy lints

frost-core/src/frost.rs, frost-core/src/frost/identifier.rs, frost-core/src/frost/keys.rs, frost-core/src/frost/round1.rs, frost-core/src/frost/round2.rs, frost-core/tests/common/vectors.rs, frost-core/tests/frost.rs, frost-core/tests/tests.rs, frost-p256/src/lib.rs, frost-p256/src/tests.rs, frost-p256/src/tests/vectors.rs, frost-p256/tests/frost.rs, frost-ristretto255/src/lib.rs, frost-ristretto255/src/tests.rs, frost-ristretto255/src/tests/vectors.rs, frost-ristretto255/tests/frost.rs
Requires #88 
Closes #55 
Things I'm not sure about:
- The commented out `test_identifier_to_scalar` test: should I delete it? Should we make `to_scalar()` public?
- Should we add a `identifier_to_scalar()` method to the trait, and add the implementation in this PR as a default implementation?
=> use Identifier instead of index

frost-core/src/batch.rs, frost-core/src/frost.rs, frost-core/src/frost/keys.rs, frost-core/src/frost/round1.rs, frost-core/src/lib.rs, frost-core/src/verifying_key.rs
Based on #96 
Closes #91 
As it stands, the RFC can be interpreted as basically requiring cofactored verification (the cofactor curves require it, and the curves without cofactor don't, so we can always just multiply by the factor even if it's 1 and it will cover both cases). Thus the current implementation already follows the RFC. But in case there is the need to override it, this PR:
- Adds `VerifySignature` method to the `Ciphersuite` trait, with a default implementation with cofactored verification
- Changes the existing `VerifyingKey.verify()` to call that
There are many possible designs here, this is just what seemed to make more sense. We could also:
- Do nothing
- Don't provide a default implementation, which would allow us to remove `Group::cofactor()` if we want, but then we'd …
=> Make verification per-ciphersuite

frost-core/README.md, frost-core/src/frost/keys.rs, frost-core/src/frost/round1.rs, frost-core/src/frost/round2.rs, frost-core/src/lib.rs, frost-core/src/signature.rs, frost-core/src/signing_key.rs, frost-core/src/tests.rs, frost-core/src/tests/vectors.rs, frost-p256/src/lib.rs, frost-ristretto255/src/lib.rs
Based on #105 
Closes #59 
Not sure about the names, these were what made sense to me, feel free to suggest other names.
=> rename keys::{Secret, Public}

frost-core/src/frost/keys.rs, frost-core/src/tests.rs
Based on #106 
Closes #47 
This changes `SharePackage` to not contain the group and participant public keys, and instead derives them from the commitments. This was already explictly done in `SecretShare.verify()` and I just changed it to return those values.
=> Derive verification share and group public key from commitments

frost-core/src/error.rs, frost-p256/src/lib.rs, frost-p256/tests/frost.rs, frost-ristretto255/src/lib.rs, frost-ristretto255/tests/frost.rs
Closes #134
While doing this I wondered if we should do the same in `serialize`, this is being currently discussed in chat, and we can do that in another PR if we want to.
=> reject identity in Group::deserialize

frost-core/src/tests.rs
A small cleanup to make the import usage consistent in the generic tests
=> cleanup imports of tests.rs

frost-core/src/scalar_mul.rs, frost-p256/tests/frost.rs
Depends on #114 
Uses the `little_endian_encoding` introduced in #114 to fix the bug described in #141.
Additionally, fixs another bug that would cause batching to fail for P-256, which was caused by the NAF size being fixed to 256. Since it's at most one element larger than the bit length, it worked for Ristretto (255) but not for P-256. I just increased it to 257.
Closes https://github.com/ZcashFoundation/frost/issues/141
=> Fix batching for P-256

frost-core/src/error.rs, frost-core/src/frost.rs, frost-core/src/frost/keys.rs, frost-core/src/frost/keys/dkg.rs, frost-core/src/frost/round1.rs, frost-core/src/frost/round2.rs, frost-core/src/verifying_key.rs, frost-ed25519/src/lib.rs, frost-p256/src/lib.rs, frost-ristretto255/src/lib.rs
Closes #167 
I decided to keep everything into a single enum to see how many items would it have.
It's a bit big but I'm not sure if it warrants having different enums for different parts. What do you think?
Also I put the `FromHex` impls behind the test flag since it's only used in tests, and did not create a specific error for them. Also not sure what is the best approach here.
=> use Error everywhere and add enums as needed

frost-core/src/frost/keys.rs, frost-core/src/lib.rs, frost-core/src/signing_key.rs, frost-p256/src/lib.rs, frost-ristretto255/src/lib.rs
This is a optional cleanup.
Upside: removes a trait method
Downside: implementers must guarantee that PartialEq/Eq for scalars are constant time.
If that does not look like a good idea, we can change this PR to simply call the global `random_nonzero` function in each ciphersuite just to avoid duplicated code, making it possible for other ciphersuites to provide their own implementation if needed.
=> remove random_nonzero from Field trait

Cargo.toml, frost-secp256k1/Cargo.toml, frost-secp256k1/README.md, frost-secp256k1/src/lib.rs, frost-secp256k1/src/tests.rs, frost-secp256k1/src/tests/vectors.json, frost-secp256k1/tests/frost.rs, frost-secp256k1/tests/proptests.rs, gendoc/src/main.rs
This is a WIP because it depends on this [k256 PR getting merged](https://github.com/RustCrypto/elliptic-curves/pull/673/commits/42a18e9e13f3bacba89af00d15ef732dbfd03d01), or using [this workaround](https://github.com/serai-dex/serai/blob/5df74ac9e28f9299e674e98d08e64c99c34e579c/crypto/ciphersuite/src/kp256.rs).
=> add secp256k1 ciphersuite

frost-core/src/frost.rs, frost-core/src/frost/keys.rs, frost-core/src/lib.rs, frost-ed25519/src/lib.rs
- Bump `-10` links to `-11`
- Remove mention to `non-zero` in hash functions - this is not enforced anymore in the spec (and they return zero with negligible probability anyway)
- Remove stale link in `cofactor()` which is not in the spec anymore but it's still being used
=> docs cleanups

frost-ed25519/src/lib.rs, frost-p256/src/lib.rs, frost-ristretto255/src/lib.rs, frost-secp256k1/src/lib.rs
For Ed448 I tried to reduce code duplication with two helper functions; here I did the same for the remaining ciphersuites
=> refactor hash implementations with hash_to_array/scalar functions

frost-core/src/frost/identifier.rs, frost-ed25519/src/tests.rs, frost-ed25519/src/tests/vectors-big-identifier.json, frost-ed448/src/tests.rs, frost-ed448/src/tests/vectors-big-identifier.json, frost-p256/src/tests.rs, frost-p256/src/tests/vectors-big-identifier.json, frost-ristretto255/src/tests.rs, frost-ristretto255/src/tests/vectors-big-identifier.json, frost-secp256k1/src/tests.rs, frost-secp256k1/src/tests/vectors-big-identifier.json
Closes #93 
I was just adding the test for large identifiers and I found out that I introduced a bug :grimacing: 
Identifiers were being compared by serializing into little endian and comparing the arrays. But that's wrong; it needs to compare the big endian arrays.
This also fixes it.
I'll also create a PR on the Sage code that generates the vectors, but I'm thinking on doing that later so it doesn't get in the way of the spec work.
=> fix Identifier ordering; add big identifier test vectors

frost-core/src/tests.rs, frost-ed25519/tests/frost.rs
After adding a similar test for [Jubjub and Pallas](https://github.com/ZcashFoundation/reddsa/pull/33/), I added a test to ensure that FROST-generate sigs can be validated by other crates.
I had great ambitions of adding this for every ciphersuite but then realized:
- Couldn't find Ed448 sig verification (Ed448-Goldilocks doesn't have it yet)
- Existing Ristretto Schnorr impls ([starsig](https://docs.rs/starsig/latest/starsig/), [schnorrkel](https://docs.rs/schnorrkel/latest/schnorrkel/index.html)) use fancy transcripts which are incompatible
- No existing P-256 Schnorr implementation (I guess we just invented it? :rofl: )
- No existing secp256k1 Schnorr implementations (Taproot is stricter)
I didn't look too hard though so we might revisit this.
=> add ed25519 interoperability test

frost-core/src/frost/keys/dkg.rs, frost-core/src/tests.rs, frost-ed25519/dkg.md, frost-ed25519/src/keys/dkg.rs, frost-ed448/dkg.md, frost-ed448/src/keys/dkg.rs, frost-p256/dkg.md, frost-p256/src/keys/dkg.rs, frost-ristretto255/dkg.md, frost-ristretto255/src/keys/dkg.rs, frost-secp256k1/dkg.md, frost-secp256k1/src/keys/dkg.rs, gendoc/src/main.rs
Closes #255 
Since `dkg.rs` are very similar between crates (just the ciphersuite "letter" changes, e.g. `<E>` or `<R>`), I changed `gendoc` to use the naive search & replace to generate the whole file for all ciphersuites instead of just copying the canonical documentation (which would require refactoring the functions in all files). At this point it should be called "gencode" or something but we can do that in a separate PR.
=> rename DKG types

frost-p256/Cargo.toml, frost-p256/src/lib.rs, frost-secp256k1/Cargo.toml, frost-secp256k1/src/lib.rs
Uses the `elliptic-curve::hash2curve::hash_to_field()` function in `H1`, `H2`, and `H3` (and `HKDF`) in place of our old implementation in `frost-secp256k1`.
=> Upgrade k256 and p256 dependencies

frost-ed25519/src/lib.rs
`gencode` does not currently support the documentation not being directly the declaration (i.e. before `#[derive]s`).
A comment was moved in one of the files which was making  `gencode` fail. This fixes that.
The proper fix is #227
=> move comment to make gencode work

frost-ed25519/src/lib.rs, frost-ed25519/tests/frost.rs, frost-ed448/src/lib.rs, frost-ed448/tests/frost.rs, frost-p256/src/lib.rs, frost-p256/tests/frost.rs, frost-rerandomized/src/lib.rs, frost-ristretto255/src/lib.rs, frost-ristretto255/tests/frost.rs, frost-secp256k1/src/lib.rs, frost-secp256k1/tests/frost.rs
=> Re-export the frost-core traits and rand-core as part of top-level impls API

.github/workflows/docs.yml
We're not publishing rustdoc with this flow, just the book
=> Don't run docs publish workflow when cargo files updated

frost-ed25519/src/keys/repairable.rs, frost-ed25519/src/lib.rs, frost-ed448/src/keys/repairable.rs, frost-ed448/src/lib.rs, frost-p256/src/keys/repairable.rs, frost-p256/src/lib.rs, frost-ristretto255/src/keys/repairable.rs, frost-ristretto255/src/lib.rs, frost-secp256k1/src/keys/repairable.rs, frost-secp256k1/src/lib.rs, gencode/src/main.rs
This changes `gencode` to handle the repairable module: it copies the documentation from `ristretto255` into the other ciphersuite crates.
It's also possible to avoid one other redundancy and copy from `frost-core` into `ristretto255` but that will requires some other tweaks so I'll do that in a separate PR.
I also found some build issues in the ciphersuite-specific repairable modules - we forgot to declare the module so it wasn't being compiled :sweat_smile:
=> Change gencode to handle repairable module; fix build issues

frost-core/src/frost.rs
The group commitment is accumulated for all the hiding commitments, saving the per-participant binding factor and their respective binding commitment for one big vartime multiscalar multiplication at the end, which is finally added to the accumulated commitment as the final group commitment.
This leads to nearly a 50% speedup at the 667/1000 end.
=> First stab at multiscalar speedup for computing group commitments

.github/workflows/main.yml
When I added the gencode step I was lazy and just added it at the end of the `rustfmt` job, which can be confusing if it fails.
This creates a separate job for it
=> split gencode job

frost-ed448/src/tests/batch.rs, frost-ed448/src/tests/proptests.rs, gencode/src/main.rs
Follow-up to #364 
Now that tests have been split we can add the ones that are similar to be generated with `gencode`.
This also ends up restoring the Ed448 batch tests, which are working now.
=> expand list of gencode-generated files

frost-core/src/error.rs, frost-core/src/frost/keys.rs, frost-core/src/frost/keys/dkg.rs, frost-core/src/frost/round2.rs, frost-core/src/tests/ciphersuite_generic.rs, frost-ristretto255/tests/integration_tests.rs
Closes https://github.com/ZcashFoundation/frost/issues/374
I'm not sure about the method name, suggestions are welcome...
This also renames some of the error fields for consistency, and removes the identifier from `InvalidSecretShare` because I realized it doesn't make sense in this case. If the secret share is invalid, then it's the Coordinator's fault (and not fault of the person who received the secret share!).
I  added the test just to `ristretto255`; it will eventually be replicated to other ciphersuites after #418 merges.
=> add Error::culprit() to make it easier to find the identifier of misbehaving participants

frost-secp256k1/Cargo.toml
The description of the `frost-secp256k1` crate currently states that it uses the Ristretto group.
=> fix curve name in frost-secp256k1 crate description

frost-core/src/lib.rs
Closes https://github.com/ZcashFoundation/frost/issues/459
I couldn't see a reason for not allowing zero, so I just updated docs.
=> fix Field::deserialize() docs

frost-core/src/scalar_mul.rs
Closes https://github.com/ZcashFoundation/frost/issues/461
I see that you assigned that to yourself @dconnolly but I created this just so we can finish addressing all the audit findings. I did the simplest thing which is just returning None. Let me know if you'd prefer something else.
=> check if iterators have the same size in multiscalar mul

.github/workflows/main.yml
Tests are much faster with `--release` so this adds the flag in CI
=> ci: run tests with --release

frost-core/src/frost/round1.rs, frost-core/src/frost/round2.rs, frost-core/src/tests/vectors.rs
Closes https://github.com/ZcashFoundation/frost/issues/454
Benchmark:
```
FROST Signing ristretto255/Round 2/2
time:   [97.239 µs 97.456 µs 97.727 µs]
change: [-28.248% -28.139% -28.010%] (p = 0.00 < 0.05)
Performance has improved.
FROST Signing ristretto255/Round 2/7
time:   [180.00 µs 181.16 µs 182.72 µs]
change: [-19.124% -18.843% -18.525%] (p = 0.00 < 0.05)
Performance has improved.
FROST Signing ristretto255/Round 2/67
time:   [1.1946 ms 1.1955 ms 1.1966 ms]
change: [-3.4950% -3.2638% -3.0433%] (p = 0.00 < 0.05)
Performance has improved.
FROST Signing ristretto255/Round 2/667
time:   [11.588 ms 11.607 ms 11.629 ms]
change: [-1.4843% -1.2623% -1.0580%] (p = 0.00 < 0.05)
Performance has improved.
```
=> improve sign() performance by caching SigningCommitments

frost-core/src/signing_key.rs, frost-core/src/tests/ciphersuite_generic.rs, frost-ed25519/tests/integration_tests.rs, frost-ed448/tests/integration_tests.rs, frost-p256/tests/integration_tests.rs, frost-ristretto255/tests/integration_tests.rs, frost-secp256k1/tests/integration_tests.rs
Closes https://github.com/ZcashFoundation/frost/issues/465
Since `VerifyingKey::new()` is private, it shouldn't possible to create one from identity, so this addresses the whole issue.
=> return error when creating a zero SigningKey

frost-core/Cargo.toml, frost-ed25519/Cargo.toml, frost-ed448/Cargo.toml, frost-p256/Cargo.toml, frost-ristretto255/Cargo.toml, frost-secp256k1/Cargo.toml
Closes https://github.com/ZcashFoundation/frost/issues/440
Also solves other issues that I found while fixing that issue:
- criterion was always being imported due to frost-core always being imported with `test-impl` activated
To test this PR you can run e.g. `cargo tree -p frost-core -e normal,build` and check the output for crates that shouldn't be there. Note that you can't omit the crate (`-p frost-core`) because it consolidates all dependencies from all projects, which includes `gencode` (which always uses serde)
=> don't import unneeded dependencies when not required

frost-core/src/batch.rs, frost-core/src/tests/batch.rs, frost-ed25519/src/tests/batch.rs, frost-ed448/src/tests/batch.rs, frost-p256/src/tests/batch.rs, frost-ristretto255/src/tests/batch.rs, frost-secp256k1/src/tests/batch.rs
Closes https://github.com/ZcashFoundation/frost/issues/445
Closes https://github.com/ZcashFoundation/frost/issues/446
=> return error when validating an empty batch

frost-core/src/frost/keys.rs, frost-core/src/tests/ciphersuite_generic.rs
Closes https://github.com/ZcashFoundation/frost/issues/456 and https://github.com/ZcashFoundation/frost/issues/460
=> check if the correct number of identifiers was provided in split()

frost-core/Cargo.toml, frost-core/src/frost.rs, frost-core/src/frost/round1.rs, frost-core/src/frost/round2.rs, frost-core/src/lib.rs, frost-ed25519/Cargo.toml, frost-ed25519/src/lib.rs, frost-ed448/Cargo.toml, frost-ed448/src/lib.rs, frost-p256/Cargo.toml, frost-p256/src/lib.rs, frost-rerandomized/Cargo.toml, frost-ristretto255/Cargo.toml, frost-secp256k1/Cargo.toml, frost-secp256k1/src/lib.rs
Depends on #492
- Document features (serde and internals for now, but also can be used for serialization if #511 merges) using document-features crate
- Enable flags to show features required to enable specific types in the docs
=> document features

frost-core/CHANGELOG.md, frost-core/src/frost/keys.rs, frost-core/src/tests/ciphersuite_generic.rs, frost-ed25519/src/lib.rs, frost-ed448/src/lib.rs, frost-p256/src/lib.rs, frost-ristretto255/src/lib.rs, frost-secp256k1/src/lib.rs
Depends on https://github.com/ZcashFoundation/frost/pull/480
Closes https://github.com/ZcashFoundation/frost/issues/458
This also changes `reconstruct()` to take `KeyPackages`s instead of `SecretShare`s which made no sense - users are expect to convert `SecretShare`s into `KeyPackage`s and store that.
=> change reconstruct() to take KeyPackages; validate size

frost-core/CHANGELOG.md, frost-core/src/error.rs, frost-core/src/frost/keys.rs, frost-core/src/frost/keys/dkg.rs, frost-core/src/frost/round2.rs, frost-core/src/tests/ciphersuite_generic.rs, frost-core/src/tests/vectors.rs, frost-ed25519/tests/helpers/samples.rs, frost-ed25519/tests/recreation_tests.rs, frost-ed25519/tests/serde_tests.rs, frost-ed448/tests/helpers/samples.rs, frost-ed448/tests/recreation_tests.rs, frost-ed448/tests/serde_tests.rs, frost-p256/tests/helpers/samples.rs, frost-p256/tests/recreation_tests.rs, frost-p256/tests/serde_tests.rs, frost-rerandomized/src/lib.rs, frost-ristretto255/tests/helpers/samples.rs, frost-ristretto255/tests/recreation_tests.rs, frost-ristretto255/tests/serde_tests.rs, frost-secp256k1/tests/helpers/samples.rs, frost-secp256k1/tests/recreation_tests.rs, frost-secp256k1/tests/serde_tests.rs
Closes https://github.com/ZcashFoundation/frost/issues/455
Not fully sure if it's worth checking this (it's not required, the signature generation would fail anyway), but it works as a second layer of validation and it seems useful for users to be able to know what is the min_signers value by getting it from the KeyPackage. Let me know what you think.
This also adds a test for trying to sign with less than min_signers share (even bypassing this new min_signers value check) which is useful in itself and makes sure we're not interpreting thresholds wrong.
=> check number of commitments in sign()

.github/workflows/docs.yml
I think this was a leftover from the zebra CI and is not needed.
=> ci: remove protoc install

frost-core/CHANGELOG.md, frost-core/src/frost/keys.rs, frost-core/src/tests/ciphersuite_generic.rs, frost-ed25519/src/lib.rs, frost-ed448/src/lib.rs, frost-p256/src/lib.rs, frost-ristretto255/src/lib.rs, frost-secp256k1/src/lib.rs
Depends on https://github.com/ZcashFoundation/frost/pull/480
Closes https://github.com/ZcashFoundation/frost/issues/458
This also changes `reconstruct()` to take `KeyPackages`s instead of `SecretShare`s which made no sense - users are expect to convert `SecretShare`s into `KeyPackage`s and store that.
=> change reconstruct() to take KeyPackages; validate size 

frost-core/src/frost.rs, frost-core/src/frost/identifier.rs, frost-core/src/frost/keys.rs, frost-core/src/frost/keys/dkg.rs, frost-core/src/frost/round1.rs, frost-core/src/frost/round2.rs, frost-core/src/verifying_key.rs, frost-ed25519/src/lib.rs, frost-ed448/src/lib.rs, frost-p256/src/lib.rs, frost-rerandomized/src/lib.rs, frost-ristretto255/src/lib.rs, frost-secp256k1/src/lib.rs
When using `derive`, serde adds bounds to (De)Serialize even to the Ciphersuite itself, even though that's not required. That is annoying because it requires us to add the bounds to all ciphersuite structs, but more importantly, is making things much harder in #525 since it needs to use the new default serialization methods which require serde.
This uses `serde(bound = "C: Ciphersuite")` to remove those bounds. See https://stackoverflow.com/questions/76107066/how-to-help-deserializer-understand-that-generics-dont-need-deserialize-bound.
Part of #525 but does not close it.
=> remove serde bounds from Ciphersuites

.github/dependabot.yml
I figured we can just omit it and assign it ourselves per availability
=> dependabot: remove hardcoded reviewer and assignee

frost-core/CHANGELOG.md, frost-core/src/identifier.rs, frost-core/src/keys.rs, frost-core/src/keys/dkg.rs, frost-core/src/lib.rs, frost-core/src/round1.rs, frost-core/src/round2.rs, frost-core/src/serialization.rs, frost-core/src/traits.rs, frost-core/src/verifying_key.rs, frost-rerandomized/src/lib.rs
As mentioned in #568 , `lib.rs` got too big so I split parts of it into `traits.rs` and `serialization.rs`.
While doing that I noticed that some types were pub but they didn't need to be, so I hid them.
=> frost-core: split part of lib.rs into traits.rs and serialization.rs

frost-core/CHANGELOG.md, frost-ed25519/src/lib.rs, frost-ed448/src/lib.rs, frost-p256/src/lib.rs, frost-ristretto255/src/lib.rs, frost-secp256k1/src/lib.rs
Small cleanup. While working on the demo noticed that we missed this. (Reexporting makes it easier for callers to use the same serde library that our crates use, without having to import it again and figuring out which version to import)
=> re-export serde in ciphersuite crates

book/src/dev/developer-guide.md, frost-core/src/keys.rs, frost-core/src/keys/dkg.rs, frost-core/src/lib.rs, frost-core/src/tests/vectors.rs
This closes #576 
Fixes publishing warnings for release v1.0.0-rc.0
=> Fix warnings

frost-core/src/keys.rs
These are needed in `reddsa` to support even Y public keys
=> create new() methods for VerifirableSecretSharingCommitment and CoefficientCommitment

frost-core/src/serialization.rs
fixes https://github.com/ZcashFoundation/frost/issues/588
=> fix deserialization issue in ciphersuite_deserialize

frost-core/src/keys.rs, frost-core/src/keys/dkg.rs, frost-core/src/tests/ciphersuite_generic.rs
Throws an error if the number of commitments is incorrect
Updates `.get(0)` to `.first()`
=> Check num of commitments against min signers

.github/workflows/main.yml, frost-core/Cargo.toml
`cargo test -p frost-core` was failing because the benchmark was failing to build, which in turn was being caused by the `criterion` dependency not being included when compiling without features.
This was not being caught because on CI we just use `cargo test`, which merges all features and would end up including `criterion`.
This was also not being caught by the all-features test because we were only doing `build` (which does not build benchmarks) and not `test` (which does build benchmarks).
This fixes the issue, and adds test-all-features to CI, which already works on each crate separately.
=> build and test each crate separately

frost-ed25519/README.md, frost-ed448/README.md, frost-p256/README.md, frost-ristretto255/README.md, frost-secp256k1/README.md
- simplify range expression
- use `key_package` variable
=> chore(docs): fix clippy warnings in examples

book/src/zcash/ywallet-demo.md
This should merge only after https://github.com/ZcashFoundation/frost-zcash-demo/pull/252 gets merged
=> docs: update demo docs for user registration

.github/workflows/main.yml
=> ci: pin nightly toolchain when using minimal-versions

frost-core/src/keys.rs
=> Add `internal` feature for `validate_num_of_signers`

frost-core/CHANGELOG.md, frost-core/src/keys/dkg.rs
=> Add missing `derive(Getters)` for `dkg::{round1, round2}`

frost-core/src/lib.rs
This PR fixes dead_code warning. I get this error when reusing frost-core in roast-core.
```
$ cargo clippy --release -p frost-core --no-default-features -F internals
Checking frost-core v2.0.0-rc.0 (/tmp/frost/frost-core)
warning: function `detect_cheater` is never used
--> frost-core/src/lib.rs:637:4
|
637 | fn detect_cheater<C: Ciphersuite>(
|    ^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```
=> chore(frost-core): fix dead_code warning

book/src/tutorial/importing.md, frost-core/CHANGELOG.md, frost-core/Cargo.toml, frost-ed25519/Cargo.toml, frost-ed448/Cargo.toml, frost-p256/Cargo.toml, frost-rerandomized/Cargo.toml, frost-ristretto255/Cargo.toml, frost-secp256k1/Cargo.toml
Update changelog and versions for release v2.0.0. This closes (#755)
=> Release v2.0.0

frost-core/CHANGELOG.md, frost-core/src/error.rs, frost-core/src/keys.rs, frost-core/src/keys/dkg.rs, frost-core/src/tests/ciphersuite_generic.rs
=> allow identifying culprit in error returned by dkg::part3()

frost-core/CHANGELOG.md
=> fix(changelog): now it's possible to identify culprit in part3(), but only in unreleased version

frost-p256/dkg.md, frost-ristretto255/dkg.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "needs an unique" to "needs a unique".
Corrected "If there is not" to "If there is no".
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files

frost-secp256k1-tr/src/lib.rs
Credit to al3x in Discord for noticing the issue.
=> secp256k1-tr: fix hashes_to_scalar to avoid panics

book/src/tutorial/importing.md
**Error:** In the "Importing and General Information" section, the sentence:  
> "Alternatively, if you would like to **user** another format such as JSON, you can enable the `serde` feature..."  
contains a typographical error where the word "**user**" should be the verb "**use**."
**Correction:**  
> "Alternatively, if you would like to **use** another format such as JSON, you can enable the `serde` feature..."
**Importance:**  
This correction addresses a verb misuse, where "user" (a noun) was incorrectly used instead of "use" (a verb). This change improves the clarity and accuracy of the text, ensuring that it properly communicates the intended instruction to the reader.
=> Typo fix Update importing.md

frost-ed25519/dkg.md, frost-ed448/dkg.md, frost-secp256k1-tr/Cargo.toml, frost-secp256k1-tr/dkg.md, frost-secp256k1-tr/src/lib.rs, frost-secp256k1/dkg.md
Also regenerates some .md files that were missing in #774
=> secp256k1-tr: fix no-std support

frost-core/src/identifier.rs, frost-ristretto255/tests/integration_tests.rs, frost-secp256k1/src/tests/deserialize.rs
=> core: prevent creating a zero identifier with deserialization

frost-core/src/keys/refresh.rs, frost-core/src/tests/ciphersuite_generic.rs, frost-core/src/tests/refresh.rs, frost-ed25519/src/lib.rs, frost-ed25519/tests/integration_tests.rs, frost-ed448/src/lib.rs, frost-ed448/tests/integration_tests.rs, frost-p256/tests/integration_tests.rs, frost-ristretto255/tests/integration_tests.rs, frost-secp256k1/src/lib.rs, frost-secp256k1/tests/integration_tests.rs
This closes #663 
This adds the refresh share functionality with DKG. It needs some tidying up but that will be done in another PR.
=> Refresh Shares with DKG

frost-secp256k1-tr/src/lib.rs, frost-secp256k1-tr/tests/integration_tests.rs
@conradoplg missed in #766
also fixes CI: `cargo run --bin gencode -- --check`
I'm sure how to fix warnings:
```
WARNING: documentation for aggregate_with_tweak is not available in base file. This can mean it's a specific type for the ciphersuite, or that there is a bug in gencode
WARNING: documentation for sign_with_tweak is not available in base file. This can mean it's a specific type for the ciphersuite, or that there is a bug in gencode
WARNING: documentation for Tweak is not available in base file. This can mean it's a specific type for the ciphersuite, or that there is a bug in gencode
WARNING: documentation for EvenY is not available in base file. This can mean it's a specific type for the ciphersuite, or that there is a bug in gencode
```
=> fix(frost-secp256k1-tr): add missing `pub mod refresh` and missing test

.github/workflows/main.yml
This turns doc warnings into errors, making sure we don't miss them.
=> ci: fail on doc warnings

frost-secp256k1-tr/src/lib.rs
I noticed that the addresses I was deriving with rust-bitcoin and the ones I created with the taptweak'd key using this library were not the same. The problem is in how the tweak is calculated in the absence of script paths.
Per [BIP-341](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki), if there are no script paths, the internal key should still be tapTweak'd by **tG, where t = TaggedHash(P_x)**. Before this commit, the internal key and the Taproot output key were the same if no script paths were used. This is because the tweak was the 0 scalar value, so Q = P + tG = P.
It is worth noting that Bitcoin's consensus rules will accept a non-taptweak'd internal key as it verifies a signature against whatever public key is used in the witness program. So the outputs are still …
=> fix(frost-secp256k1-tr): empty merkle root tweak should still hash the x-only pk

frost-core/src/keys/dkg.rs
The new SecretPackage serialization code is breaking when the `internals` feature is disabled
=> frost-core: fix visibility of coefficients()

frost-core/src/keys/repairable.rs, frost-core/src/lib.rs, frost-core/src/tests/refresh.rs, frost-core/src/tests/repairable.rs
`know `  -  `known `
`might useful` -  `might be useful`
`recover `  -  `recovered` х2
=> docs: correction comments

book/src/SUMMARY.md, book/src/zcash/server.md, book/src/zcash/ywallet-demo.md
Closes #805 
This is a draft because it is incomplete. It just adds a section about FROST Server. We need to update the Ywallet Tutorial itself, and point to the FROST Server section when it talks about the server.
=> book: add FROST Server section

Cargo.toml, book/src/dev/release-checklist.md, frost-core/Cargo.toml, frost-ed25519/Cargo.toml, frost-ed448/Cargo.toml, frost-p256/Cargo.toml, frost-rerandomized/Cargo.toml, frost-ristretto255/Cargo.toml, frost-secp256k1-tr/Cargo.toml, frost-secp256k1/Cargo.toml, gencode/Cargo.toml
=> chore(deps): improve organization of workspace (root Cargo.toml)

frost-core/src/keys.rs, frost-core/src/tests/vss_commitment.rs, frost-ed25519/src/tests/vss_commitment.rs, frost-ed448/src/tests/vss_commitment.rs, frost-p256/src/tests/vss_commitment.rs, frost-ristretto255/src/tests/vss_commitment.rs, frost-secp256k1-tr/src/tests/vss_commitment.rs, frost-secp256k1/src/tests/vss_commitment.rs
=> feat(frost-core): add (de)serialization for `VerifiableSecretSharingSharingSharingCommitment`

book/src/SUMMARY.md, book/src/frost.md
Resolves #722
Added a new section to the documentation that explains FROST network topologies:
- Signing topologies (Centralized and Distributed)
- DKG topologies (Full Mesh and Star)
- ASCII diagrams for visual representation
- Pros and cons for each topology
- Guidelines for topology selection
Changes:
- Added "Network Topologies" section in frost.md
- Updated SUMMARY.md with new section link
=> docs: Add network topologies section with diagrams

book/src/SUMMARY.md, book/src/frost.md, book/src/tutorial/dkg.md, book/src/zcash/ywallet-demo.md
Two people asked about this so it seems useful to emphasize.
I also fixed an issue in the summary (pointing to a section breaks the side menu), moved the new topology subsection to the end of the file where it makes more sense, and fixed some quotes in the demo section.
=> docs: add warning about encrypted channel for DKG

frost-core/src/tests/vectors_dkg.rs
my `#![no_std]` fork can no longer pass CI because of this:
```
Compiling frost-core v2.1.0 (/home/runner/work/frost/frost/frost-core)
error[E0412]: cannot find type `String` in this scope
--> frost-core/src/tests/vectors_dkg.rs:156:18
|
156 |     sender_num: &String,
|                  ^^^^^^
```
@conradoplg
=> chore(frost-core): import `String` from `alloc`

frost-core/src/keys.rs, frost-core/src/traits.rs
This commit adds a new `post_generate` method to the Ciphersuite trait, similar to the existing `post_dkg` method. It allows ciphersuites to customize the key generation process by post-processing the output of key generation.
This is especially useful for the RedPallas ciphersuite, which needs to perform special processing on keys to enable some optimizations. The method is integrated into the `TryFrom<SecretShare>` implementation for `KeyPackage`, which ensures it will be called when users convert their secret shares into key packages.
Fixes #844
=> Add post_generate to Ciphersuite trait

frost-core/src/error.rs
No idea why clippy is only catching this now, but we have a error struct that was not being used.
=> core: remove unused error
